### ISSUE TITLE
Could you please give a more general link such as Google Cloud drive or OneDrive?

### ISSUE THREAD

**Issue by shallweiwei** [tanguymagne/UVDoc-Dataset#1]
Hello, I'm very interested in your work. I think the UVDoc dataset is very valuable.
But I found that this link was sometimes slow to download, even 10kb/s.

**Comment by shallweiwei** [comment]
After downloading about 1GB, it showed that there was a network problem and thus interrupted my download.
I really need a new link. Thank you!

**Comment by FloorVerhoeven** [comment]
Hello, we just tested the download and got 50-100 MB/s download speed so it is more likely to be an issue with your internet connection. Please try downloading over another internet connection and use a cabled rather than wireless connection if possible. Due to the size we unfortunately cannot upload it to Google Drive/OneDrive.

**Comment by shallweiwei** [comment]
Well, it's a little sad, and it probably has to do with some Internet restrictions I have here
